FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge@sha256:86fb5b55fbada2eeca29a4da135a2bec274caa4bc561791d6c2207fdd217a34b

RUN dpkg --add-architecture arm64 && \
  apt-get update && \
  apt-get install --assume-yes \
  glibc-source \
  build-essential 

RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y software-properties-common && \
  rm -rf /var/lib/apt/lists/*

RUN add-apt-repository ppa:pipewire-debian/pipewire-upstream -y

RUN apt-get install --assume-yes \
  libpipewire-0.3-dev:arm64

